"""Candidate-safe molecule and crystal viewer artifacts."""

from __future__ import annotations

from html import escape
from typing import Any


def molecule_viewer_report(candidate_document: dict[str, Any]) -> dict[str, Any]:
    """Build viewer targets from candidate-only evidence-resolution records."""

    targets = []
    for candidate in candidate_document.get("candidates", []):
        structures = []
        for side, structure in sorted(candidate.get("structure_candidates", {}).items()):
            if not structure.get("url"):
                continue
            structures.append(
                {
                    "side": side,
                    "proposed_form_label": structure.get("proposed_form_label", "not_recorded"),
                    "source_database": structure.get("source_database", "not_recorded"),
                    "source_id": structure.get("source_id", "not_recorded"),
                    "viewer_url": structure["url"],
                    "cif_url": structure.get("cif_url"),
                    "space_group": structure.get("space_group", "not_recorded"),
                    "license": structure.get("license", "not_recorded"),
                    "has_disorder": structure.get("has_disorder", "not_recorded"),
                    "viewer_kind": _viewer_kind(structure),
                    "coordinate_policy": "remote_source_only_no_coordinates_embedded",
                    "claim_label": "candidate_unverified",
                    "coordinates_embedded": False,
                }
            )
        if structures:
            targets.append(
                {
                    "pair_id": candidate["pair_id"],
                    "candidate_status": candidate.get("candidate_status", "not_recorded"),
                    "promotion_decision": candidate.get("promotion_decision", "not_recorded"),
                    "proposed_stability_ordering": candidate.get("proposed_stability_ordering", "not_recorded"),
                    "structure_count": len(structures),
                    "structures": structures,
                }
            )

    structure_count = sum(target["structure_count"] for target in targets)
    return {
        "schema_version": "0.1.0",
        "status": "molecule_viewers_recorded" if targets else "molecule_viewers_empty",
        "target_count": len(targets),
        "structure_viewer_count": structure_count,
        "targets": targets,
        "policy": [
            "Viewer artifacts are candidate-public navigation aids, not benchmark evidence.",
            "No atom coordinates, CIF text, or gated source blocks are embedded in generated viewer pages.",
            "External viewer links must preserve the source page license and citation context.",
            "Records remain candidate_unverified until source, form, license, and stability evidence are reviewed.",
        ],
    }


def molecule_viewer_markdown(report: dict[str, Any], *, viewer_pages: dict[str, str] | None = None) -> str:
    """Render the viewer target registry as Markdown."""

    viewer_pages = viewer_pages or {}
    lines = [
        "# CrystalProbe Molecule Viewers",
        "",
        f"- Status: `{report['status']}`",
        f"- Viewer targets: `{report['target_count']}`",
        f"- Structure viewers: `{report['structure_viewer_count']}`",
        "",
        "## Viewer Targets",
        "",
        "| Pair | Side | Form | Source | Viewer | Claim Label | Coordinate Policy |",
        "|---|---|---|---|---|---|---|",
    ]
    for target in report.get("targets", []):
        pair_id = target["pair_id"]
        for structure in target["structures"]:
            link = f"[Open COD JSmol]({structure['viewer_url']})"
            lines.append(
                f"| `{pair_id}` | `{structure['side']}` | {structure['proposed_form_label']} | "
                f"`{structure['source_id']}` | {link} | `{structure['claim_label']}` | "
                f"`{structure['coordinate_policy']}` |"
            )
    lines.extend(["", "## Generated Pages", ""])
    if viewer_pages:
        for pair_id, path in sorted(viewer_pages.items()):
            lines.append(f"- `{pair_id}`: [{path}]({path})")
    else:
        lines.append("- Viewer pages are generated by `scripts/build_molecule_viewer_report.py`.")
    lines.extend(["", "## Policy", ""])
    lines.extend(f"- {line}" for line in report.get("policy", []))
    return "\n".join(lines).rstrip() + "\n"


def molecule_viewer_html(report: dict[str, Any], *, pair_id: str) -> str:
    """Render a standalone HTML viewer page for one pair."""

    target = _target_for_pair(report, pair_id)
    structures = target.get("structures", []) if target else []
    cards = "\n".join(_structure_card(structure) for structure in structures)
    policy_items = "\n".join(f"<li>{escape(line)}</li>" for line in report.get("policy", []))
    title = f"CrystalProbe Viewer: {pair_id}"
    if not cards:
        cards = "<p class=\"empty\">No viewer targets are recorded for this pair.</p>"
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{escape(title)}</title>
  <style>
    :root {{
      color-scheme: light;
      --ink: #1f2937;
      --muted: #5f6b7a;
      --line: #d7dde5;
      --panel: #f7f9fb;
      --accent: #087f8c;
      --warn: #9a5b00;
      --bg: #ffffff;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      font-family: Inter, Segoe UI, Arial, sans-serif;
      color: var(--ink);
      background: var(--bg);
      line-height: 1.45;
    }}
    header, main {{
      width: min(1180px, calc(100% - 32px));
      margin: 0 auto;
    }}
    header {{
      padding: 28px 0 16px;
      border-bottom: 1px solid var(--line);
    }}
    h1 {{
      margin: 0 0 8px;
      font-size: 26px;
      line-height: 1.15;
      letter-spacing: 0;
    }}
    .subhead {{
      margin: 0;
      color: var(--muted);
      max-width: 850px;
    }}
    .badge-row {{
      display: flex;
      gap: 8px;
      flex-wrap: wrap;
      margin-top: 14px;
    }}
    .badge {{
      border: 1px solid var(--line);
      border-radius: 999px;
      padding: 4px 10px;
      font-size: 13px;
      background: var(--panel);
    }}
    .badge.warn {{
      border-color: #f0c77b;
      color: var(--warn);
      background: #fff8ea;
    }}
    main {{
      padding: 22px 0 36px;
    }}
    .viewer-grid {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
      gap: 18px;
    }}
    .viewer-card {{
      border: 1px solid var(--line);
      border-radius: 8px;
      overflow: hidden;
      background: #fff;
    }}
    .viewer-card h2 {{
      font-size: 18px;
      margin: 0;
      padding: 14px 16px 4px;
      letter-spacing: 0;
    }}
    .meta {{
      display: grid;
      grid-template-columns: 130px 1fr;
      gap: 6px 10px;
      padding: 8px 16px 14px;
      font-size: 14px;
    }}
    .meta dt {{
      color: var(--muted);
    }}
    .meta dd {{
      margin: 0;
      min-width: 0;
      overflow-wrap: anywhere;
    }}
    .remote-frame {{
      width: 100%;
      height: 430px;
      border: 0;
      border-top: 1px solid var(--line);
      background: var(--panel);
    }}
    .actions {{
      display: flex;
      gap: 10px;
      flex-wrap: wrap;
      padding: 12px 16px 16px;
      border-top: 1px solid var(--line);
    }}
    .button {{
      display: inline-flex;
      align-items: center;
      min-height: 36px;
      padding: 0 12px;
      border: 1px solid var(--accent);
      border-radius: 6px;
      color: var(--accent);
      text-decoration: none;
      font-weight: 600;
      font-size: 14px;
    }}
    .policy {{
      margin-top: 20px;
      padding: 16px;
      background: var(--panel);
      border: 1px solid var(--line);
      border-radius: 8px;
    }}
    .policy h2 {{
      margin: 0 0 8px;
      font-size: 17px;
      letter-spacing: 0;
    }}
    .policy ul {{
      margin: 0;
      padding-left: 20px;
    }}
    .empty {{
      padding: 18px;
      border: 1px solid var(--line);
      border-radius: 8px;
      background: var(--panel);
    }}
  </style>
</head>
<body>
  <header>
    <h1>{escape(title)}</h1>
    <p class="subhead">Remote source viewers for candidate structures. This page is intentionally a navigation layer: it does not embed CIF text or atom coordinates. If a source blocks inline display, use the Open COD JSmol button.</p>
    <div class="badge-row">
      <span class="badge warn">candidate_unverified</span>
      <span class="badge">promotion: {escape(str(target.get('promotion_decision', 'not_recorded') if target else 'not_recorded'))}</span>
      <span class="badge">ordering: {escape(str(target.get('proposed_stability_ordering', 'not_recorded') if target else 'not_recorded'))}</span>
    </div>
  </header>
  <main>
    <section class="viewer-grid" aria-label="Remote molecule viewers">
{cards}
    </section>
    <section class="policy">
      <h2>Visualization Policy</h2>
      <ul>
{policy_items}
      </ul>
    </section>
  </main>
</body>
</html>
"""


def _target_for_pair(report: dict[str, Any], pair_id: str) -> dict[str, Any] | None:
    for target in report.get("targets", []):
        if target.get("pair_id") == pair_id:
            return target
    return None


def _structure_card(structure: dict[str, Any]) -> str:
    viewer_url = escape(str(structure["viewer_url"]), quote=True)
    cif_url = structure.get("cif_url")
    cif_link = ""
    if cif_url:
        cif_link = (
            f'<a class="button" href="{escape(str(cif_url), quote=True)}" '
            'target="_blank" rel="noopener noreferrer">Open CIF Source</a>'
        )
    return f"""      <article class="viewer-card" data-claim-label="{escape(str(structure['claim_label']), quote=True)}">
        <h2>{escape(str(structure['side']))}: {escape(str(structure['proposed_form_label']))}</h2>
        <dl class="meta">
          <dt>Source</dt><dd>{escape(str(structure['source_id']))}</dd>
          <dt>Viewer type</dt><dd>{escape(str(structure['viewer_kind']))}</dd>
          <dt>Space group</dt><dd>{escape(str(structure['space_group']))}</dd>
          <dt>License</dt><dd>{escape(str(structure['license']))}</dd>
          <dt>Disorder</dt><dd>{escape(str(structure['has_disorder']))}</dd>
          <dt>Policy</dt><dd>{escape(str(structure['coordinate_policy']))}</dd>
        </dl>
        <iframe class="remote-frame" src="{viewer_url}" title="Remote COD/JSmol viewer for {escape(str(structure['source_id']), quote=True)}" loading="lazy" referrerpolicy="no-referrer"></iframe>
        <div class="actions">
          <a class="button" href="{viewer_url}" target="_blank" rel="noopener noreferrer">Open COD JSmol</a>
          {cif_link}
        </div>
      </article>"""


def _viewer_kind(structure: dict[str, Any]) -> str:
    source_database = str(structure.get("source_database", "")).upper()
    if source_database == "COD":
        return "cod_jsmol_remote_page"
    return "external_remote_source_page"
